// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29505_Subscription_Data

import (
	_ "embed"
)

//go:embed TS29505_Subscription_Data.yaml
var SpecYaml []byte
