// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29551_Nnef_PFDmanagement

import (
	_ "embed"
)

//go:embed TS29551_Nnef_PFDmanagement.yaml
var SpecYaml []byte
