// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29518_Namf_Communication

import (
	_ "embed"
)

//go:embed TS29518_Namf_Communication.yaml
var SpecYaml []byte
