// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29523_Npcf_EventExposure

import (
	_ "embed"
)

//go:embed TS29523_Npcf_EventExposure.yaml
var SpecYaml []byte
