// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package influence

//go:generate go run github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml ../modSpecs/TS29522_TrafficInfluence.yaml
