// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29509_Nausf_SoRProtection

import (
	_ "embed"
)

//go:embed TS29509_Nausf_SoRProtection.yaml
var SpecYaml []byte
