// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29122_ResourceManagementOfBdt

import (
	_ "embed"
)

//go:embed TS29122_ResourceManagementOfBdt.yaml
var SpecYaml []byte
