// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS32291_Nchf_ConvergedCharging

import (
	_ "embed"
)

//go:embed TS32291_Nchf_ConvergedCharging.yaml
var SpecYaml []byte
