// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29504_Nudr_GroupIDmap

import (
	_ "embed"
)

//go:embed TS29504_Nudr_GroupIDmap.yaml
var SpecYaml []byte
