// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29517_Naf_EventExposure

import (
	_ "embed"
)

//go:embed TS29517_Naf_EventExposure.yaml
var SpecYaml []byte
