// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package TS29512_Npcf_SMPolicyControl

import (
	_ "embed"
)

//go:embed TS29512_Npcf_SMPolicyControl.yaml
var SpecYaml []byte
