apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nssaa-aaa-gateway
  namespace: nssaa
spec:
  host: nssaa-aaa-gateway
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 200
        maxRequestsPerConnection: 50
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 10s
      maxEjectionPercent: 100
    tls:
      mode: ISTIO_MUTUAL
