//go:build e2e
// +build e2e

// Server-initiated (AMF callback) integration test for per-UE debug tracing.
//
// Exercises flow direction (c):
//
//	AAA-S → aaa-gw (RAR over RADIUS) → biz
//
// This test verifies that:
// 1. A forward session creates a session correlation entry in Redis with GPSI
// 2. The RAR can be triggered from aaa-sim to aaa-gateway
// 3. Forward flow events are emitted correctly
//
// Full server-initiated event verification (callback flow to AMF) requires
// additional implementation in aaa-gateway for RAR reception and is pending.
//
// Spec: TS 29.526 §7.2.4-5 (Server-Initiated Callbacks)
package e2e

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/require"

	"github.com/operator/nssAAF/internal/logging"
	"github.com/operator/nssAAF/internal/proto"
)

const (
	callbackGPSI = "msisdn-208046999999001"
)

func TestDebugFullFlow_AMFCallback(t *testing.T) {
	if os.Getenv("RUN_E2E") != "1" {
		t.Skip("set RUN_E2E=1 to run")
	}
	require.NoError(t, ComposeRunning("aaa-sim"))
	h := NewHarnessForTest(t)

	gpsiHash := logging.HashGPSI(callbackGPSI)
	gpsiStream := "nssaa:debug:stream:" + gpsiHash

	rdb := h.Redis()
	require.NoError(t, rdb.Del(context.Background(), gpsiStream).Err())

	// Seed a forward session.
	body := fmt.Sprintf(`{"gpsi":"%s","snssai":{"sst":1,"sd":"000001"},"eapIdRsp":"dGVzdA=="}`, callbackGPSI)
	postNSSAAAuth(t, body)

	// Verify session correlation entry was created with GPSI.
	realSessionID := lookupSessionIDForGPSI(t, rdb, callbackGPSI)
	require.NotEmpty(t, realSessionID, "no Redis session correlation entry found for gpsi=%s", callbackGPSI)

	time.Sleep(500 * time.Millisecond)

	// Trigger RAR from aaa-sim to exercise server-initiated flow.
	driver := NewAaaSimDriver("aaa-sim")
	driver.TriggerRAR(t, realSessionID, "172.0.3.15:1812")

	// Verify forward flow events are present.
	required := []string{
		"http-gw:http.request",
		"http-gw:http.request.exit",
		"biz:http.request",
		"biz:pg.session.create",
		"biz:http.request.out",
		"biz:http.request.exit",
		"aaa-gw:aaa.session_corr.write",
		"aaa-gw:aaa.radius.forward",
		"aaa-gw:redis.session_corr.write",
		"aaa-gw:aaa.handle_forward",
	}

	deadline := time.Now().Add(5 * time.Second)
	backoff := 100 * time.Millisecond
	var events []redis.XMessage
	for time.Now().Before(deadline) {
		var err error
		events, err = rdb.XRange(context.Background(), gpsiStream, "-", "+").Result()
		require.NoError(t, err)
		if hasRequiredDebugEvents(events, required) {
			break
		}
		time.Sleep(backoff)
		backoff *= 2
		if backoff > 800*time.Millisecond {
			backoff = 800 * time.Millisecond
		}
	}
	require.GreaterOrEqual(t, len(events), len(required),
		"timed out waiting for events on stream %s (got %d events)", gpsiStream, len(events))

	present := map[string]bool{}
	for _, e := range events {
		svc, _ := e.Values["svc"].(string)
		op, _ := e.Values["op"].(string)
		present[svc+":"+op] = true
	}
	for _, want := range required {
		require.True(t, present[want], "missing event %s (have: %v)", want, keys(present))
	}
}

// lookupSessionIDForAuthCtx scans Redis for nssaa:session:* keys and returns
// the session_id suffix (the part after the prefix) whose stored
// SessionCorrEntry.AuthCtxID matches the given authCtxID.
//
// Returns the empty string if no matching entry is found within the timeout.
// Production aaa-gw writes this entry during ForwardEAP; the forward POST
// above drives that path.
func lookupSessionIDForAuthCtx(t *testing.T, rdb *redis.Client, authCtxID string) string {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		var cursor uint64
		for {
			keys, nextCursor, err := rdb.Scan(ctx, cursor, proto.SessionCorrKeyPrefix+"*", 100).Result()
			if err != nil {
				t.Logf("redis scan: %v", err)
				break
			}
			for _, key := range keys {
				data, err := rdb.Get(ctx, key).Bytes()
				if err != nil {
					continue
				}
				var entry proto.SessionCorrEntry
				if err := json.Unmarshal(data, &entry); err != nil {
					continue
				}
				if entry.AuthCtxID == authCtxID {
					return key[len(proto.SessionCorrKeyPrefix):]
				}
			}
			cursor = nextCursor
			if cursor == 0 {
				break
			}
		}
		time.Sleep(100 * time.Millisecond)
	}
	return ""
}

// lookupSessionIDForGPSI scans Redis for a session correlation entry matching the
// given GPSI and returns the session_id. This is needed because the authCtxID
// is dynamically generated by the server and can't be known in advance.
func lookupSessionIDForGPSI(t *testing.T, rdb *redis.Client, gpsi string) string {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		var cursor uint64
		for {
			keys, nextCursor, err := rdb.Scan(ctx, cursor, proto.SessionCorrKeyPrefix+"*", 100).Result()
			if err != nil {
				t.Logf("redis scan: %v", err)
				break
			}
			for _, key := range keys {
				data, err := rdb.Get(ctx, key).Bytes()
				if err != nil {
					continue
				}
				var entry proto.SessionCorrEntry
				if err := json.Unmarshal(data, &entry); err != nil {
					continue
				}
				if entry.GPSI == gpsi {
					return key[len(proto.SessionCorrKeyPrefix):]
				}
			}
			cursor = nextCursor
			if cursor == 0 {
				break
			}
		}
		time.Sleep(100 * time.Millisecond)
	}
	return ""
}
